name = "Hyde-14"
license = "MIT"
licenselink = "https://github.com/lroguet/hyde-14/blob/master/LICENSE.md"
description = "An elegant two-column and mobile first theme."
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.14

[author]
    name = "Ludovic Roguet"
    homepage = "https://fourteenislands.io"

[original]
    author =  "spf13"
    homepage = "http://spf13.com"
    repo = "https://github.com/spf13/hyde"
